In [1]:
import numpy as np

In [3]:
a = np.arange(10)

In [4]:
a[1:5]

array([1, 2, 3, 4])

In [5]:
a[2:8:2]

array([2, 4, 6])

In [7]:
# 反向取出全部
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [8]:
a[:3], a[3:]

(array([0, 1, 2]), array([3, 4, 5, 6, 7, 8, 9]))

2D Slice

In [9]:
b = np.arange(20).reshape(4, 5)

In [10]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [11]:
b[1:3, 2:4]

array([[ 7,  8],
       [12, 13]])